name: Pack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pack
      run: |
        ./fill.sh
        rm songs/*.sample
        ls
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Songbook
        path: |
          res
          songs
          *.html
